name = "partyserver-automerge"
main = "party/automerge-partyserver/index.ts"
compatibility_date = "2024-04-19"

legacy_assets = "public"

[[durable_objects.bindings]]
name = "Automerge"
class_name = "AutomergeServer"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["AutomergeServer"]